version: "3.8"
services:
  mongodbiqcookcore:
    image: mongo
    container_name: mongodbiqcookcore
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
    volumes:
      - dbdataiqcookcore1:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - "27020:27017"
#    expose:
#      - "27020"
    restart: unless-stopped
    networks:
      private: {}
      public: {}
networks:
  private:
    internal: true
    name: private
  public:
    internal: false
    name: public
volumes:
  dbdataiqcookcore1:
